Repository i-four-people/MSA-LogisticsHub, pull requests merged in 2024-12, with the labels that each got.

#3 Chore/#1 create eureka server
  .gitignore
  server/.gitattributes
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/logistcshub/server/ServerApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/com/logistcshub/server/ServerApplicationTests.java
Labels: Chore

#4 chore: add eureka gateway
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/logistcshub/gateway/GatewayApplication.java
  gateway/src/main/java/com/logistcshub/gateway/filter/CustomPostFilter.java
  gateway/src/main/java/com/logistcshub/gateway/filter/CustomPreFilter.java
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/logistcshub/gateway/GatewayApplicationTests.java
Labels: Chore

#10 Chore: 주문 서비스 모듈 셋팅
  order/.gitattributes
  order/.gitignore
  order/build.gradle
  order/gradle/wrapper/gradle-wrapper.jar
  order/gradle/wrapper/gradle-wrapper.properties
  order/gradlew
  order/gradlew.bat
  order/settings.gradle
  order/src/main/java/com/logistics/order/OrderApplication.java
  order/src/main/resources/application-db.yml
  order/src/main/resources/application.yml
  order/src/test/java/com/logistics/order/OrderApplicationTests.java
Labels: Chore

#13 chore: set hub service module
  gateway/src/main/resources/application.yml
  hub/.gitattributes
  hub/.gitignore
  hub/build.gradle
  hub/gradle/wrapper/gradle-wrapper.jar
  hub/gradle/wrapper/gradle-wrapper.properties
  hub/gradlew
  hub/gradlew.bat
  hub/settings.gradle
  hub/src/main/java/com/logistcshub/hub/HubApplication.java
  hub/src/main/resources/application-db.yml
  hub/src/main/resources/application.yml
  hub/src/test/java/com/logistcshub/hub/HubApplicationTests.java
Labels: Chore

#17 User 모듈 및 로그인 / 회원가입 기능 추가
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/gradlew.bat
  user/settings.gradle
  user/src/main/java/com/logistcshub/user/UserApplication.java
  user/src/main/java/com/logistcshub/user/application/dtos/TokenDto.java
  user/src/main/java/com/logistcshub/user/application/dtos/UserDto.java
  user/src/main/java/com/logistcshub/user/application/jwt/CustomAuthPreFilter.java
  user/src/main/java/com/logistcshub/user/application/jwt/JwtUtil.java
  user/src/main/java/com/logistcshub/user/application/security/UserDetailsImpl.java
  user/src/main/java/com/logistcshub/user/application/security/UserDetailsServiceImpl.java
  user/src/main/java/com/logistcshub/user/application/service/AuthService.java
  user/src/main/java/com/logistcshub/user/application/service/UserService.java
  user/src/main/java/com/logistcshub/user/domain/model/User.java
  user/src/main/java/com/logistcshub/user/domain/model/UserRoleEnum.java
  user/src/main/java/com/logistcshub/user/domain/repository/UserRepository.java
  user/src/main/java/com/logistcshub/user/infrastructure/common/ApiResponse.java
  user/src/main/java/com/logistcshub/user/infrastructure/common/MessageType.java
  user/src/main/java/com/logistcshub/user/infrastructure/configuration/WebSecurity.java
  user/src/main/java/com/logistcshub/user/presentation/controller/AuthController.java
  user/src/main/java/com/logistcshub/user/presentation/controller/UserController.java
  user/src/main/java/com/logistcshub/user/presentation/request/LoginRequest.java
  user/src/main/java/com/logistcshub/user/presentation/request/SignupRequest.java
  user/src/main/resources/application.yml
  user/src/test/java/com/logistcshub/user/UserApplicationTests.java
  user/test.http
Labels: Feat

#22 Feat: area CRUD 기능 추가
  hub/src/main/java/com/logistcshub/hub/area/application/config/AddAreaListInserter.java
  hub/src/main/java/com/logistcshub/hub/area/application/dtos/AddAreaResponseDto.java
  hub/src/main/java/com/logistcshub/hub/area/application/dtos/AreaResponseDto.java
  hub/src/main/java/com/logistcshub/hub/area/application/dtos/DeleteAreaResponseDto.java
  hub/src/main/java/com/logistcshub/hub/area/application/dtos/UpdateAreaResponseDto.java
  hub/src/main/java/com/logistcshub/hub/area/application/service/AreaService.java
  hub/src/main/java/com/logistcshub/hub/area/domain/model/Area.java
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/City.java
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/State.java
  hub/src/main/java/com/logistcshub/hub/area/domain/repository/AreaFindRepository.java
  hub/src/main/java/com/logistcshub/hub/area/domain/repository/AreaRepository.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/AreaFindRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/AreaRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/JpaAreaRepository.java
  hub/src/main/java/com/logistcshub/hub/area/presentation/AreaController.java
  hub/src/main/java/com/logistcshub/hub/area/presentation/request/AddAreaRequestDto.java
  hub/src/main/java/com/logistcshub/hub/area/presentation/request/UpdateAreaRequestDto.java
  hub/src/main/java/com/logistcshub/hub/area/presentation/type/AreaSearchType.java
  hub/src/main/java/com/logistcshub/hub/area/presentation/type/SortType.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/BaseEntity.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/SuccessResponse.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/type/ResponseMessage.java
  hub/src/main/java/com/logistcshub/hub/common/exception/GlobalExceptionHandler.java
  hub/src/main/java/com/logistcshub/hub/common/exception/RestApiException.java
  hub/src/main/java/com/logistcshub/hub/common/exception/application/dtos/ErrorResponse.java
  hub/src/main/java/com/logistcshub/hub/common/exception/application/type/ErrorCode.java
  hub/src/main/java/com/logistcshub/hub/common/infrastructure/config/JpaConfig.java
Labels: Feat

#27 Feat: 주문 서비스 crud api 기능 추가
  order/src/main/java/com/logistics/order/application/dto/SearchParameter.java
  order/src/main/java/com/logistics/order/application/dto/company/CompanyResponse.java
  order/src/main/java/com/logistics/order/application/dto/event/OrderDeleteEvent.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderCreateRequest.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderDeleteResponse.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderDetailResponse.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderResponse.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderUpdateRequest.java
  order/src/main/java/com/logistics/order/application/dto/product/ProductResponse.java
  order/src/main/java/com/logistics/order/application/dto/product/ProductStockResponse.java
  order/src/main/java/com/logistics/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/logistics/order/domain/model/Order.java
  order/src/main/java/com/logistics/order/domain/repository/OrderRepository.java
  order/src/main/java/com/logistics/order/domain/service/OrderService.java
  order/src/main/java/com/logistics/order/infrastructure/client/CompanyClient.java
  order/src/main/java/com/logistics/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/logistics/order/infrastructure/config/RabbitMQConfig.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryCustom.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryCustomImpl.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/logistics/order/presentation/controller/OrderApiController.java
  order/src/test/java/com/logistics/order/application/service/OrderServiceImplTest.java
Labels: Feat

#25 Feat: 허브 생성 기능 추가
  gateway/src/main/resources/application.yml
  hub/build.gradle
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/City.java
  hub/src/main/java/com/logistcshub/hub/area/domain/repository/AreaRepository.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/AreaRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/JpaAreaRepository.java
  hub/src/main/java/com/logistcshub/hub/common/config/KakaoMapConfig.java
  hub/src/main/java/com/logistcshub/hub/common/config/RestTemplateConfig.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/KakaoAddressDto.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/KakaoMapResponseDto.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/KakaoRoadAddressDto.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/type/ResponseMessage.java
  hub/src/main/java/com/logistcshub/hub/common/exception/application/type/ErrorCode.java
  hub/src/main/java/com/logistcshub/hub/hub/application/dtos/AddHubResponseDto.java
  hub/src/main/java/com/logistcshub/hub/hub/application/service/HubService.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/mode/Hub.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/HubController.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/request/AddHubRequestDto.java
  hub/src/main/resources/application-db.yml
Labels: Feat

#31 Chore: 배송 서비스 모듈 셋팅
  delivery/.gitattributes
  delivery/.gitignore
  delivery/build.gradle
  delivery/gradle/wrapper/gradle-wrapper.jar
  delivery/gradle/wrapper/gradle-wrapper.properties
  delivery/gradlew
  delivery/gradlew.bat
  delivery/settings.gradle
  delivery/src/main/java/com/logistics/delivery/DeliveryApplication.java
  delivery/src/main/resources/application-db.yml
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/logistics/delivery/DeliveryApplicationTests.java
  gateway/src/main/resources/application.yml
Labels: Chore

#40 Chore: product 모듈 생성 및 설정
  product/src/main/resources/application-db.yml
  product/src/main/resources/application.yml
Labels: Chore

#37 Feat: 허브 검색 기능 추가
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/City.java
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/State.java
  hub/src/main/java/com/logistcshub/hub/hub/application/dtos/HubResponseDto.java
  hub/src/main/java/com/logistcshub/hub/hub/application/dtos/HubSearchDto.java
  hub/src/main/java/com/logistcshub/hub/hub/application/service/HubService.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubSearchRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubSearchRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/HubController.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/request/type/HubSearchType.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/request/type/SortType.java
Labels: Feat

#38 Feat: User 상세 정보 조회 / HubManager 추가
  gateway/src/main/resources/application.yml
  user/build.gradle
  user/src/main/java/com/logistcshub/user/UserApplication.java
  user/src/main/java/com/logistcshub/user/application/DeliveryManagerMapper.java
  user/src/main/java/com/logistcshub/user/application/client/HubClient.java
  user/src/main/java/com/logistcshub/user/application/dtos/DeliveryManagerDto.java
  user/src/main/java/com/logistcshub/user/application/dtos/HubDto.java
  user/src/main/java/com/logistcshub/user/application/dtos/HubResponse.java
  user/src/main/java/com/logistcshub/user/application/service/DeliveryManagerService.java
  user/src/main/java/com/logistcshub/user/application/service/HubManagerService.java
  user/src/main/java/com/logistcshub/user/application/service/UserService.java
  user/src/main/java/com/logistcshub/user/domain/model/DeliveryManager.java
  user/src/main/java/com/logistcshub/user/domain/model/DeliveryManagerType.java
  user/src/main/java/com/logistcshub/user/domain/model/DeliveryStatus.java
  user/src/main/java/com/logistcshub/user/domain/model/HubManager.java
  user/src/main/java/com/logistcshub/user/domain/model/User.java
  user/src/main/java/com/logistcshub/user/domain/repository/DeliveryManagerRepository.java
  user/src/main/java/com/logistcshub/user/domain/repository/HubManagerRepository.java
  user/src/main/java/com/logistcshub/user/infrastructure/common/AuditEntity.java
  user/src/main/java/com/logistcshub/user/infrastructure/common/SearchResponse.java
  user/src/main/java/com/logistcshub/user/infrastructure/configuration/WebSecurity.java
  user/src/main/java/com/logistcshub/user/infrastructure/repository/UserRepositoryCustom.java
  user/src/main/java/com/logistcshub/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/logistcshub/user/presentation/controller/DeliveryManagerController.java
  user/src/main/java/com/logistcshub/user/presentation/controller/HubManagerController.java
  user/src/main/java/com/logistcshub/user/presentation/controller/UserController.java
  user/src/main/java/com/logistcshub/user/presentation/request/DeliveryManagerCreate.java
  user/src/main/java/com/logistcshub/user/presentation/request/HubManagerRequest.java
  user/src/main/java/com/logistcshub/user/presentation/response/HubManagerResponse.java
  user/test.http
Labels: Feat, Chore

#45 Feat: hub-transfer entity 생성 및 hub 자동 생성 config 추가
  hub/src/main/java/com/logistcshub/hub/common/exception/application/type/ErrorCode.java
  hub/src/main/java/com/logistcshub/hub/hub/application/config/AddHubListInserter.java
  hub/src/main/java/com/logistcshub/hub/hub/application/service/HubService.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/service/HubTransferService.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/model/HubTransfer.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/repository/HubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/HubTransferRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/JpaHubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/HubTransferController.java
Labels: Feat, Chore

#46 43 feat product crud 기능 구현
  company/src/main/java/com/logistcshub/company/domain/repository/CompanyRepositoryCustom.java
  product/src/main/java/com/logiticshub/product/application/dto/ProductResponseDto.java
  product/src/main/java/com/logiticshub/product/domain/model/Product.java
  product/src/main/java/com/logiticshub/product/domain/repository/ProductRepository.java
  product/src/main/java/com/logiticshub/product/domain/repository/ProductRepositoryCustom.java
  product/src/main/java/com/logiticshub/product/domain/service/ProductService.java
  product/src/main/java/com/logiticshub/product/infrastructure/ProductRepositoryImpl.java
  product/src/main/java/com/logiticshub/product/infrastructure/QueryDSLConfig.java
  product/src/main/java/com/logiticshub/product/presentation/controller/ProductController.java
  product/src/main/java/com/logiticshub/product/presentation/request/ProductRequestDto.java
  product/src/main/java/com/logiticshub/product/presentation/response/ApiResponse.java
  product/src/main/java/com/logiticshub/product/presentation/response/MessageType.java
Labels: Feat

#47 33 refactor company 조회 pagedmodel로 변경
  company/src/main/java/com/logistcshub/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/logistcshub/company/domain/repository/CompanyRepositoryCustom.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/infrastructure/config/CompanyRepositoryCustomImpl.java
  company/src/main/java/com/logistcshub/company/infrastructure/config/QueryDSLConfig.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
Labels: Refactor

#51 Chore: Product 모듈 build.gradle 등 포함 업로드
  product/.gitattributes
  product/.gitignore
  product/build.gradle
  product/gradle/wrapper/gradle-wrapper.jar
  product/gradle/wrapper/gradle-wrapper.properties
  product/gradlew
  product/gradlew.bat
  product/settings.gradle
  product/src/main/java/com/logiticshub/product/ProductApplication.java
  product/src/test/java/com/logiticshub/product/ProductApplicationTests.java
Labels: Chore

#50 Feat: hub-transfer 등록 기능 추가
  hub/src/main/java/com/logistcshub/hub/common/config/KakaoRoadApiConfig.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/KakaoResponse.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/KakaoRoadRequestDto.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/dtos/KakaoRoadResponseDto.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/type/ResponseMessage.java
  hub/src/main/java/com/logistcshub/hub/common/exception/application/type/ErrorCode.java
  hub/src/main/java/com/logistcshub/hub/hub/application/config/AddHubListInserter.java
  hub/src/main/java/com/logistcshub/hub/hub/application/service/HubService.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/dtos/AddHubTransferResponseDto.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/service/HubTransferService.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/model/HubTransfer.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/repository/HubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/HubTransferRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/JpaHubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/HubTransferController.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/request/AddHubTransferRequestDto.java
  hub/src/main/resources/application-db.yml
  hub/src/main/resources/application.yml
Labels: Feat

#54 Feat: FeignClient을 통한 Company, Product 생성 기능 수정
  company/src/main/java/com/logistcshub/company/CompanyApplication.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
  gateway/src/main/resources/application.yml
  product/src/main/java/com/logiticshub/product/ProductApplication.java
  product/src/main/java/com/logiticshub/product/application/client/CompanyClient.java
  product/src/main/java/com/logiticshub/product/application/dto/CompanyResponseDto.java
  product/src/main/java/com/logiticshub/product/domain/service/ProductService.java
  product/src/main/java/com/logiticshub/product/presentation/request/ProductRequestDto.java
Labels: Feat

#58 55 feat kakao api를 사용해 company 주소에 따른 위도 경도 저장
  company/src/main/java/com/logistcshub/company/domain/model/Company.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/infrastructure/config/RestApiException.java
  company/src/main/java/com/logistcshub/company/infrastructure/config/RestTemplateConfig.java
  company/src/main/java/com/logistcshub/company/presentation/request/CompanyRequestDto.java
  company/src/main/java/com/logistcshub/company/presentation/response/CompanyResponseDto.java
  company/src/main/java/com/logistcshub/company/presentation/response/ErrorCode.java
  company/src/main/resources/application.yml
Labels: Feat, Refactor

#56 Feat: Hub-Transfer 수정, 삭제, 상세 조회 기능 추가
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/AreaRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/JpaAreaRepository.java
  hub/src/main/java/com/logistcshub/hub/common/domain/model/type/ResponseMessage.java
  hub/src/main/java/com/logistcshub/hub/common/exception/application/type/ErrorCode.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/HubController.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/dtos/DeleteHubTransferResponseDto.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/dtos/HubTransferResponseDto.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/dtos/UpdateHubTransferResponseDto.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/service/HubTransferService.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/model/HubTransfer.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/repository/HubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/HubTransferRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/JpaHubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/HubTransferController.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/request/UpdateTransferRequestDto.java
Labels: Feat, Fix

#60 Feat: Hub-Transfer 검색 기능 추가 및 서버 실행 시 초기 연결 되어 있는 허브 inserter 추가
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  hub/build.gradle
  hub/src/main/java/com/logistcshub/hub/common/domain/model/type/ResponseMessage.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/config/AddHubTransferInserter.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/dtos/HubTransferPageDto.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/service/HubTransferService.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/model/HubTransfer.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/domain/repository/HubTransferRepository.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/infrastructure/HubTransferRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/HubTransferController.java
Labels: Feat, Chore

#64 Feat: Company 주소와 위도 경도로 허브 배정 기능 추가
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/City.java
  hub/src/main/java/com/logistcshub/hub/area/domain/repository/AreaRepository.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/AreaRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/area/infrastructure/JpaAreaRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/application/service/HubService.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/HubController.java
  hub/src/main/resources/import.sql
Labels: Feat

#68 65 feat hub service를 통해 company의 hubid 배정
  company/src/main/java/com/logistcshub/company/application/client/HubClient.java
  company/src/main/java/com/logistcshub/company/application/dto/HubResponseDto.java
  company/src/main/java/com/logistcshub/company/application/dto/ResponseMessage.java
  company/src/main/java/com/logistcshub/company/application/dto/SuccessResponse.java
  company/src/main/java/com/logistcshub/company/domain/model/Company.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
  company/src/main/java/com/logistcshub/company/presentation/request/CompanyRequestDto.java
  product/src/main/java/com/logiticshub/product/domain/model/Product.java
  product/src/main/java/com/logiticshub/product/domain/service/ProductService.java
  product/src/main/java/com/logiticshub/product/presentation/controller/ProductController.java
Labels: Feat

#74 Feat: redis를 사용한 캐싱 처리
  company/build.gradle
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/infrastructure/config/RedisConfig.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
  company/src/main/resources/application.yml
  product/build.gradle
  product/src/main/java/com/logiticshub/product/application/client/CompanyClient.java
  product/src/main/java/com/logiticshub/product/application/dto/CompanyResponseDto.java
  product/src/main/java/com/logiticshub/product/domain/model/Product.java
  product/src/main/java/com/logiticshub/product/domain/service/ProductService.java
  product/src/main/java/com/logiticshub/product/infrastructure/RedisConfig.java
  product/src/main/java/com/logiticshub/product/presentation/controller/ProductController.java
  product/src/main/resources/application-db.yml
  product/src/main/resources/application.yml
Labels: Feat

#76 Feat: company, product 리스트 조회
  company/src/main/java/com/logistcshub/company/application/dto/CompanyResponse.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
  product/src/main/java/com/logiticshub/product/application/dto/ProductResponse.java
  product/src/main/java/com/logiticshub/product/domain/service/ProductService.java
  product/src/main/java/com/logiticshub/product/presentation/controller/ProductController.java
Labels: Feat

#72 Feat: 배송 이동 경로 생성 및 배송과 연결
  delivery/src/main/java/com/logistics/delivery/application/dto/event/consume/OrderCreateConsume.java
  delivery/src/main/java/com/logistics/delivery/application/dto/hub/HubToHubResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/user/DeliveryManagerResponse.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryRouteServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/domain/model/DeliveryRoute.java
  delivery/src/main/java/com/logistics/delivery/domain/model/RouteStatus.java
  delivery/src/main/java/com/logistics/delivery/domain/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/logistics/delivery/domain/service/DeliveryManagerService.java
  delivery/src/main/java/com/logistics/delivery/domain/service/DeliveryRouteService.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/DeliveryManagerClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/listener/OrderEventListener.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRouteRepositoryImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/JpaDeliveryRouteRepository.java
  delivery/src/main/resources/application.yml
  order/src/main/java/com/logistics/order/application/dto/event/EventType.java
  order/src/main/java/com/logistics/order/application/dto/event/consume/DeliveryCreateConsume.java
  order/src/main/java/com/logistics/order/application/message/OrderMessageListener.java
  order/src/main/java/com/logistics/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/logistics/order/application/util/EventUtil.java
  order/src/main/java/com/logistics/order/domain/model/Order.java
  order/src/main/java/com/logistics/order/domain/service/OrderService.java
  order/src/main/java/com/logistics/order/presentation/exception/ErrorCode.java
  order/src/main/resources/application-infra.yml
Labels: Feat

#78 Feat: 배송 담당자 생성하는 스케줄링 추가 및 배송 담당자 배정 후 슬랙 이벤트 발행하는 로직 추가
  delivery/src/main/java/com/logistics/delivery/DeliveryApplication.java
  delivery/src/main/java/com/logistics/delivery/application/dto/event/EventType.java
  delivery/src/main/java/com/logistics/delivery/application/dto/event/SlackCreateEvent.java
  delivery/src/main/java/com/logistics/delivery/application/dto/event/consume/SlackCreateConsume.java
  delivery/src/main/java/com/logistics/delivery/application/dto/user/DeliveryManagerResponse.java
  delivery/src/main/java/com/logistics/delivery/application/message/SlackMessageListener.java
  delivery/src/main/java/com/logistics/delivery/application/scheduler/DeliveryAssignmentScheduler.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/domain/model/DeliveryRoute.java
  delivery/src/main/java/com/logistics/delivery/domain/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/config/RabbitMQConfig.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/config/RabbitMQProperties.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRouteRepositoryImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/JpaDeliveryRouteRepository.java
  delivery/src/main/resources/application-infra.yml
  delivery/src/main/resources/application.yml
Labels: Feat

#82 80 feat companproduct 권한 체크 추가
  company/src/main/java/com/logistcshub/company/application/AuthorizationUtil.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
  product/src/main/java/com/logiticshub/product/application/AuthorizationUtil.java
  product/src/main/java/com/logiticshub/product/domain/service/ProductService.java
  product/src/main/java/com/logiticshub/product/presentation/controller/ProductController.java
Labels: Feat

#83 Feat: 배송 RUD API 추가
  delivery/src/main/java/com/logistics/delivery/application/dto/PageResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/SearchParameter.java
  delivery/src/main/java/com/logistics/delivery/application/dto/delivery/DeliveryDeleteResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/delivery/DeliveryDetailResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/delivery/DeliveryResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/delivery/DeliveryRouteResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/deliverymanager/DeliveryManagerResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/deliverymanager/DeliveryManagerType.java
  delivery/src/main/java/com/logistics/delivery/application/dto/deliverymanager/DeliveryManagerUpdateRequest.java
  delivery/src/main/java/com/logistics/delivery/application/dto/event/SlackCreateEvent.java
  delivery/src/main/java/com/logistics/delivery/application/dto/event/consume/OrderDeleteConsume.java
  delivery/src/main/java/com/logistics/delivery/application/dto/hub/HubResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/order/OrderResponse.java
  delivery/src/main/java/com/logistics/delivery/application/message/DeliveryMessageListener.java
  delivery/src/main/java/com/logistics/delivery/application/scheduler/DeliveryAssignmentScheduler.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryRouteServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/domain/model/Delivery.java
  delivery/src/main/java/com/logistics/delivery/domain/model/DeliveryRoute.java
  delivery/src/main/java/com/logistics/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/logistics/delivery/domain/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/logistics/delivery/domain/service/DeliveryRouteService.java
  delivery/src/main/java/com/logistics/delivery/domain/service/DeliveryService.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/DeliveryManagerClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/OrderClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRouteRepositoryImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/JpaDeliveryRepository.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/JpaDeliveryRouteRepository.java
  delivery/src/main/java/com/logistics/delivery/presentation/controller/DeliveryApiController.java
  delivery/src/main/java/com/logistics/delivery/presentation/exception/ErrorCode.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderDeleteResponse.java
  order/src/main/java/com/logistics/order/application/dto/order/OrderResponse.java
  order/src/main/java/com/logistics/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/logistics/order/domain/model/Order.java
  order/src/main/java/com/logistics/order/infrastructure/repository/JpaOrderRepository.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryImpl.java
Labels: Feat

#87 Feat: 슬랙 메세지 전송 기능 추가, gemini api 기능 추가, role validation 변경 및 hubTest.http 파일 추가
  delivery/build.gradle
  delivery/src/main/java/com/logistics/delivery/application/dto/company/CompanyResponse.java
  delivery/src/main/java/com/logistics/delivery/application/dto/gemini/GeminiResponseDTO.java
  delivery/src/main/java/com/logistics/delivery/application/dto/order/OrderDetailResponse.java
  delivery/src/main/java/com/logistics/delivery/application/message/SlackMessageListener.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/SlackServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/logistics/delivery/domain/service/SlackService.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/HubClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/client/OrderClient.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/config/RestTemplateConfig.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRouteRepositoryImpl.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/logistics/delivery/application/service/SlackServiceImplTest.java
  hub/hubTest.http
  hub/src/main/java/com/logistcshub/hub/area/application/service/AreaService.java
  hub/src/main/java/com/logistcshub/hub/area/domain/model/type/City.java
  hub/src/main/java/com/logistcshub/hub/area/presentation/AreaController.java
  hub/src/main/java/com/logistcshub/hub/hub/application/service/HubService.java
  hub/src/main/java/com/logistcshub/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/HubRepositoryImpl.java
  hub/src/main/java/com/logistcshub/hub/hub/infrastructure/JpaHubRepository.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/HubController.java
  hub/src/main/java/com/logistcshub/hub/hub/presentation/request/HubIdsDto.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/application/service/HubTransferService.java
  hub/src/main/java/com/logistcshub/hub/hub_transfer/presentation/HubTransferController.java
  order/src/main/java/com/logistics/order/infrastructure/repository/JpaOrderRepository.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryImpl.java
Labels: Feat, Test

#85 Feat: 배송 및 배송 이동 경로의 배송 상태 관리
  delivery/src/main/java/com/logistics/delivery/application/dto/delivery/DeliveryStatusUpdateRequest.java
  delivery/src/main/java/com/logistics/delivery/application/dto/delivery/RouteStatusUpdateRequest.java
  delivery/src/main/java/com/logistics/delivery/application/scheduler/DeliveryStatusScheduler.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryRouteServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/application/service/DeliveryServiceImpl.java
  delivery/src/main/java/com/logistics/delivery/domain/model/Delivery.java
  delivery/src/main/java/com/logistics/delivery/domain/model/DeliveryRoute.java
  delivery/src/main/java/com/logistics/delivery/domain/model/DeliveryStatus.java
  delivery/src/main/java/com/logistics/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/logistics/delivery/domain/service/DeliveryRouteService.java
  delivery/src/main/java/com/logistics/delivery/domain/service/DeliveryService.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/logistics/delivery/infrastructure/repository/JpaDeliveryRepository.java
  delivery/src/main/java/com/logistics/delivery/presentation/controller/DeliveryApiController.java
  delivery/src/main/java/com/logistics/delivery/presentation/controller/DeliveryRouteApiController.java
  delivery/src/main/java/com/logistics/delivery/presentation/exception/ErrorCode.java
  order/src/main/java/com/logistics/order/application/dto/SearchParameter.java
  order/src/main/java/com/logistics/order/application/service/OrderServiceImpl.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryCustomImpl.java
  order/src/main/java/com/logistics/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/logistics/order/presentation/auth/AuthContext.java
  order/src/main/java/com/logistics/order/presentation/auth/AuthHeader.java
  order/src/main/java/com/logistics/order/presentation/auth/AuthHeaderArgumentResolver.java
  order/src/main/java/com/logistics/order/presentation/auth/AuthHeaderFilter.java
  order/src/main/java/com/logistics/order/presentation/auth/AuthHeaderInfo.java
  order/src/main/java/com/logistics/order/presentation/config/WebConfig.java
  order/src/main/java/com/logistics/order/presentation/controller/OrderApiController.java
Labels: Feat

#91 Feat: 이름으로 company 조회 기능 추가
  company/src/main/java/com/logistcshub/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/logistcshub/company/domain/service/CompanyService.java
  company/src/main/java/com/logistcshub/company/presentation/controller/CompanyController.java
Labels: Feat

#89 Refactor: Exception Handling
  user/src/main/java/com/logistcshub/user/application/service/AuthService.java
  user/src/main/java/com/logistcshub/user/application/service/DeliveryManagerService.java
  user/src/main/java/com/logistcshub/user/application/service/HubManagerService.java
  user/src/main/java/com/logistcshub/user/application/service/UserService.java
  user/src/main/java/com/logistcshub/user/common/exception/GlobalExceptionHandler.java
  user/src/main/java/com/logistcshub/user/common/exception/InvalidMethodResponse.java
  user/src/main/java/com/logistcshub/user/common/exception/UserException.java
  user/src/main/java/com/logistcshub/user/common/message/ExceptionMessage.java
  user/src/main/java/com/logistcshub/user/domain/model/AuditEntity.java
  user/src/main/java/com/logistcshub/user/infrastructure/config/CacheConfig.java
  user/src/main/java/com/logistcshub/user/infrastructure/config/RedisConfig.java
  user/userTest.http
Labels: Refactor

#96 Chore: 환경 변수 설정
  user/.env
  user/.gitignore
  user/src/main/java/com/logistcshub/user/application/service/DeliveryManagerService.java
  user/src/main/resources/application-db.yml
  user/src/main/resources/application.yml
Labels: Fix, Chore
